name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++-14 clang++-18

      - name: Test-gcc-14
        run: cmake --workflow gcc-14

      - name: Test-clang-18
        run: cmake --workflow clang-18
